// Generated by gencpp from file slam_msg/Keyframes.msg
// DO NOT EDIT!


#ifndef SLAM_MSG_MESSAGE_KEYFRAMES_H
#define SLAM_MSG_MESSAGE_KEYFRAMES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <slam_msg/Keyframe.h>

namespace slam_msg
{
template <class ContainerAllocator>
struct Keyframes_
{
  typedef Keyframes_<ContainerAllocator> Type;

  Keyframes_()
    : header()
    , keyframes()  {
    }
  Keyframes_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , keyframes(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::slam_msg::Keyframe_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::slam_msg::Keyframe_<ContainerAllocator> >::other >  _keyframes_type;
  _keyframes_type keyframes;





  typedef boost::shared_ptr< ::slam_msg::Keyframes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slam_msg::Keyframes_<ContainerAllocator> const> ConstPtr;

}; // struct Keyframes_

typedef ::slam_msg::Keyframes_<std::allocator<void> > Keyframes;

typedef boost::shared_ptr< ::slam_msg::Keyframes > KeyframesPtr;
typedef boost::shared_ptr< ::slam_msg::Keyframes const> KeyframesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slam_msg::Keyframes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slam_msg::Keyframes_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::slam_msg::Keyframes_<ContainerAllocator1> & lhs, const ::slam_msg::Keyframes_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.keyframes == rhs.keyframes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::slam_msg::Keyframes_<ContainerAllocator1> & lhs, const ::slam_msg::Keyframes_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace slam_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::slam_msg::Keyframes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slam_msg::Keyframes_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slam_msg::Keyframes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slam_msg::Keyframes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slam_msg::Keyframes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slam_msg::Keyframes_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slam_msg::Keyframes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a4a320307c3c27d6044230b27f893913";
  }

  static const char* value(const ::slam_msg::Keyframes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa4a320307c3c27d6ULL;
  static const uint64_t static_value2 = 0x044230b27f893913ULL;
};

template<class ContainerAllocator>
struct DataType< ::slam_msg::Keyframes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slam_msg/Keyframes";
  }

  static const char* value(const ::slam_msg::Keyframes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slam_msg::Keyframes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"Keyframe[] keyframes\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: slam_msg/Keyframe\n"
"int32 id\n"
"float64[3] position\n"
"float32[4] rotation\n"
;
  }

  static const char* value(const ::slam_msg::Keyframes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slam_msg::Keyframes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.keyframes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Keyframes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slam_msg::Keyframes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slam_msg::Keyframes_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "keyframes[]" << std::endl;
    for (size_t i = 0; i < v.keyframes.size(); ++i)
    {
      s << indent << "  keyframes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::slam_msg::Keyframe_<ContainerAllocator> >::stream(s, indent + "    ", v.keyframes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLAM_MSG_MESSAGE_KEYFRAMES_H
