// Generated by gencpp from file dislam_msgs/GetInitMap.msg
// DO NOT EDIT!


#ifndef DISLAM_MSGS_MESSAGE_GETINITMAP_H
#define DISLAM_MSGS_MESSAGE_GETINITMAP_H

#include <ros/service_traits.h>


#include <dislam_msgs/GetInitMapRequest.h>
#include <dislam_msgs/GetInitMapResponse.h>


namespace dislam_msgs
{

struct GetInitMap
{

typedef GetInitMapRequest Request;
typedef GetInitMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetInitMap
} // namespace dislam_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dislam_msgs::GetInitMap > {
  static const char* value()
  {
    return "e9fa119186dfec39a98e0ec6980aefe6";
  }

  static const char* value(const ::dislam_msgs::GetInitMap&) { return value(); }
};

template<>
struct DataType< ::dislam_msgs::GetInitMap > {
  static const char* value()
  {
    return "dislam_msgs/GetInitMap";
  }

  static const char* value(const ::dislam_msgs::GetInitMap&) { return value(); }
};


// service_traits::MD5Sum< ::dislam_msgs::GetInitMapRequest> should match
// service_traits::MD5Sum< ::dislam_msgs::GetInitMap >
template<>
struct MD5Sum< ::dislam_msgs::GetInitMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dislam_msgs::GetInitMap >::value();
  }
  static const char* value(const ::dislam_msgs::GetInitMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dislam_msgs::GetInitMapRequest> should match
// service_traits::DataType< ::dislam_msgs::GetInitMap >
template<>
struct DataType< ::dislam_msgs::GetInitMapRequest>
{
  static const char* value()
  {
    return DataType< ::dislam_msgs::GetInitMap >::value();
  }
  static const char* value(const ::dislam_msgs::GetInitMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dislam_msgs::GetInitMapResponse> should match
// service_traits::MD5Sum< ::dislam_msgs::GetInitMap >
template<>
struct MD5Sum< ::dislam_msgs::GetInitMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dislam_msgs::GetInitMap >::value();
  }
  static const char* value(const ::dislam_msgs::GetInitMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dislam_msgs::GetInitMapResponse> should match
// service_traits::DataType< ::dislam_msgs::GetInitMap >
template<>
struct DataType< ::dislam_msgs::GetInitMapResponse>
{
  static const char* value()
  {
    return DataType< ::dislam_msgs::GetInitMap >::value();
  }
  static const char* value(const ::dislam_msgs::GetInitMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DISLAM_MSGS_MESSAGE_GETINITMAP_H
