// Generated by gencpp from file dislam_msgs/InterPRs.msg
// DO NOT EDIT!


#ifndef DISLAM_MSGS_MESSAGE_INTERPRS_H
#define DISLAM_MSGS_MESSAGE_INTERPRS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <dislam_msgs/InterPR.h>

namespace dislam_msgs
{
template <class ContainerAllocator>
struct InterPRs_
{
  typedef InterPRs_<ContainerAllocator> Type;

  InterPRs_()
    : seq(0)
    , InterPRs()  {
    }
  InterPRs_(const ContainerAllocator& _alloc)
    : seq(0)
    , InterPRs(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _seq_type;
  _seq_type seq;

   typedef std::vector< ::dislam_msgs::InterPR_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::dislam_msgs::InterPR_<ContainerAllocator> >::other >  _InterPRs_type;
  _InterPRs_type InterPRs;





  typedef boost::shared_ptr< ::dislam_msgs::InterPRs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dislam_msgs::InterPRs_<ContainerAllocator> const> ConstPtr;

}; // struct InterPRs_

typedef ::dislam_msgs::InterPRs_<std::allocator<void> > InterPRs;

typedef boost::shared_ptr< ::dislam_msgs::InterPRs > InterPRsPtr;
typedef boost::shared_ptr< ::dislam_msgs::InterPRs const> InterPRsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dislam_msgs::InterPRs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dislam_msgs::InterPRs_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dislam_msgs::InterPRs_<ContainerAllocator1> & lhs, const ::dislam_msgs::InterPRs_<ContainerAllocator2> & rhs)
{
  return lhs.seq == rhs.seq &&
    lhs.InterPRs == rhs.InterPRs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dislam_msgs::InterPRs_<ContainerAllocator1> & lhs, const ::dislam_msgs::InterPRs_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dislam_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dislam_msgs::InterPRs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dislam_msgs::InterPRs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dislam_msgs::InterPRs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dislam_msgs::InterPRs_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dislam_msgs::InterPRs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dislam_msgs::InterPRs_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dislam_msgs::InterPRs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "526823748d66ee65dc49e2e597f3ca63";
  }

  static const char* value(const ::dislam_msgs::InterPRs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x526823748d66ee65ULL;
  static const uint64_t static_value2 = 0xdc49e2e597f3ca63ULL;
};

template<class ContainerAllocator>
struct DataType< ::dislam_msgs::InterPRs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dislam_msgs/InterPRs";
  }

  static const char* value(const ::dislam_msgs::InterPRs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dislam_msgs::InterPRs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 seq\n"
"InterPR[] InterPRs\n"
"================================================================================\n"
"MSG: dislam_msgs/InterPR\n"
"int64 id0\n"
"int64 id1\n"
"bool isAerial\n"
"bool isChecked\n"
"geometry_msgs/Pose id0Pose\n"
"geometry_msgs/Pose factorPose\n"
"sensor_msgs/PointCloud2 keyframe\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
;
  }

  static const char* value(const ::dislam_msgs::InterPRs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dislam_msgs::InterPRs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.seq);
      stream.next(m.InterPRs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InterPRs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dislam_msgs::InterPRs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dislam_msgs::InterPRs_<ContainerAllocator>& v)
  {
    s << indent << "seq: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.seq);
    s << indent << "InterPRs[]" << std::endl;
    for (size_t i = 0; i < v.InterPRs.size(); ++i)
    {
      s << indent << "  InterPRs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::dislam_msgs::InterPR_<ContainerAllocator> >::stream(s, indent + "    ", v.InterPRs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DISLAM_MSGS_MESSAGE_INTERPRS_H
