// Generated by gencpp from file dislam_msgs/InterPR.msg
// DO NOT EDIT!


#ifndef DISLAM_MSGS_MESSAGE_INTERPR_H
#define DISLAM_MSGS_MESSAGE_INTERPR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <sensor_msgs/PointCloud2.h>

namespace dislam_msgs
{
template <class ContainerAllocator>
struct InterPR_
{
  typedef InterPR_<ContainerAllocator> Type;

  InterPR_()
    : id0(0)
    , id1(0)
    , isAerial(false)
    , isChecked(false)
    , id0Pose()
    , factorPose()
    , keyframe()  {
    }
  InterPR_(const ContainerAllocator& _alloc)
    : id0(0)
    , id1(0)
    , isAerial(false)
    , isChecked(false)
    , id0Pose(_alloc)
    , factorPose(_alloc)
    , keyframe(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _id0_type;
  _id0_type id0;

   typedef int64_t _id1_type;
  _id1_type id1;

   typedef uint8_t _isAerial_type;
  _isAerial_type isAerial;

   typedef uint8_t _isChecked_type;
  _isChecked_type isChecked;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _id0Pose_type;
  _id0Pose_type id0Pose;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _factorPose_type;
  _factorPose_type factorPose;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _keyframe_type;
  _keyframe_type keyframe;





  typedef boost::shared_ptr< ::dislam_msgs::InterPR_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dislam_msgs::InterPR_<ContainerAllocator> const> ConstPtr;

}; // struct InterPR_

typedef ::dislam_msgs::InterPR_<std::allocator<void> > InterPR;

typedef boost::shared_ptr< ::dislam_msgs::InterPR > InterPRPtr;
typedef boost::shared_ptr< ::dislam_msgs::InterPR const> InterPRConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dislam_msgs::InterPR_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dislam_msgs::InterPR_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dislam_msgs::InterPR_<ContainerAllocator1> & lhs, const ::dislam_msgs::InterPR_<ContainerAllocator2> & rhs)
{
  return lhs.id0 == rhs.id0 &&
    lhs.id1 == rhs.id1 &&
    lhs.isAerial == rhs.isAerial &&
    lhs.isChecked == rhs.isChecked &&
    lhs.id0Pose == rhs.id0Pose &&
    lhs.factorPose == rhs.factorPose &&
    lhs.keyframe == rhs.keyframe;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dislam_msgs::InterPR_<ContainerAllocator1> & lhs, const ::dislam_msgs::InterPR_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dislam_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dislam_msgs::InterPR_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dislam_msgs::InterPR_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dislam_msgs::InterPR_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dislam_msgs::InterPR_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dislam_msgs::InterPR_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dislam_msgs::InterPR_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dislam_msgs::InterPR_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5b4beb7f05ebd7c0cec036a4e93d3373";
  }

  static const char* value(const ::dislam_msgs::InterPR_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5b4beb7f05ebd7c0ULL;
  static const uint64_t static_value2 = 0xcec036a4e93d3373ULL;
};

template<class ContainerAllocator>
struct DataType< ::dislam_msgs::InterPR_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dislam_msgs/InterPR";
  }

  static const char* value(const ::dislam_msgs::InterPR_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dislam_msgs::InterPR_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 id0\n"
"int64 id1\n"
"bool isAerial\n"
"bool isChecked\n"
"geometry_msgs/Pose id0Pose\n"
"geometry_msgs/Pose factorPose\n"
"sensor_msgs/PointCloud2 keyframe\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
;
  }

  static const char* value(const ::dislam_msgs::InterPR_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dislam_msgs::InterPR_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id0);
      stream.next(m.id1);
      stream.next(m.isAerial);
      stream.next(m.isChecked);
      stream.next(m.id0Pose);
      stream.next(m.factorPose);
      stream.next(m.keyframe);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InterPR_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dislam_msgs::InterPR_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dislam_msgs::InterPR_<ContainerAllocator>& v)
  {
    s << indent << "id0: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id0);
    s << indent << "id1: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id1);
    s << indent << "isAerial: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isAerial);
    s << indent << "isChecked: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isChecked);
    s << indent << "id0Pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.id0Pose);
    s << indent << "factorPose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.factorPose);
    s << indent << "keyframe: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.keyframe);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DISLAM_MSGS_MESSAGE_INTERPR_H
