// Generated by gencpp from file pyslam_msgs/Loop.msg
// DO NOT EDIT!


#ifndef PYSLAM_MSGS_MESSAGE_LOOP_H
#define PYSLAM_MSGS_MESSAGE_LOOP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace pyslam_msgs
{
template <class ContainerAllocator>
struct Loop_
{
  typedef Loop_<ContainerAllocator> Type;

  Loop_()
    : id0()
    , id1()
    , pose()  {
    }
  Loop_(const ContainerAllocator& _alloc)
    : id0(_alloc)
    , id1(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int64_t, typename ContainerAllocator::template rebind<int64_t>::other >  _id0_type;
  _id0_type id0;

   typedef std::vector<int64_t, typename ContainerAllocator::template rebind<int64_t>::other >  _id1_type;
  _id1_type id1;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::pyslam_msgs::Loop_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pyslam_msgs::Loop_<ContainerAllocator> const> ConstPtr;

}; // struct Loop_

typedef ::pyslam_msgs::Loop_<std::allocator<void> > Loop;

typedef boost::shared_ptr< ::pyslam_msgs::Loop > LoopPtr;
typedef boost::shared_ptr< ::pyslam_msgs::Loop const> LoopConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pyslam_msgs::Loop_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pyslam_msgs::Loop_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pyslam_msgs::Loop_<ContainerAllocator1> & lhs, const ::pyslam_msgs::Loop_<ContainerAllocator2> & rhs)
{
  return lhs.id0 == rhs.id0 &&
    lhs.id1 == rhs.id1 &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pyslam_msgs::Loop_<ContainerAllocator1> & lhs, const ::pyslam_msgs::Loop_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pyslam_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pyslam_msgs::Loop_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pyslam_msgs::Loop_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pyslam_msgs::Loop_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pyslam_msgs::Loop_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pyslam_msgs::Loop_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pyslam_msgs::Loop_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pyslam_msgs::Loop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36672ea1b2db4ae845d4fdab55058cb8";
  }

  static const char* value(const ::pyslam_msgs::Loop_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36672ea1b2db4ae8ULL;
  static const uint64_t static_value2 = 0x45d4fdab55058cb8ULL;
};

template<class ContainerAllocator>
struct DataType< ::pyslam_msgs::Loop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pyslam_msgs/Loop";
  }

  static const char* value(const ::pyslam_msgs::Loop_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pyslam_msgs::Loop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64[]  id0\n"
"int64[]  id1\n"
"geometry_msgs/Pose pose\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::pyslam_msgs::Loop_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pyslam_msgs::Loop_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id0);
      stream.next(m.id1);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Loop_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pyslam_msgs::Loop_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pyslam_msgs::Loop_<ContainerAllocator>& v)
  {
    s << indent << "id0[]" << std::endl;
    for (size_t i = 0; i < v.id0.size(); ++i)
    {
      s << indent << "  id0[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.id0[i]);
    }
    s << indent << "id1[]" << std::endl;
    for (size_t i = 0; i < v.id1.size(); ++i)
    {
      s << indent << "  id1[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.id1[i]);
    }
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PYSLAM_MSGS_MESSAGE_LOOP_H
