// Generated by gencpp from file dislam_msgs/GetInitMapRequest.msg
// DO NOT EDIT!


#ifndef DISLAM_MSGS_MESSAGE_GETINITMAPREQUEST_H
#define DISLAM_MSGS_MESSAGE_GETINITMAPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dislam_msgs
{
template <class ContainerAllocator>
struct GetInitMapRequest_
{
  typedef GetInitMapRequest_<ContainerAllocator> Type;

  GetInitMapRequest_()
    : initState(false)  {
    }
  GetInitMapRequest_(const ContainerAllocator& _alloc)
    : initState(false)  {
  (void)_alloc;
    }



   typedef uint8_t _initState_type;
  _initState_type initState;





  typedef boost::shared_ptr< ::dislam_msgs::GetInitMapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dislam_msgs::GetInitMapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetInitMapRequest_

typedef ::dislam_msgs::GetInitMapRequest_<std::allocator<void> > GetInitMapRequest;

typedef boost::shared_ptr< ::dislam_msgs::GetInitMapRequest > GetInitMapRequestPtr;
typedef boost::shared_ptr< ::dislam_msgs::GetInitMapRequest const> GetInitMapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dislam_msgs::GetInitMapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dislam_msgs::GetInitMapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dislam_msgs::GetInitMapRequest_<ContainerAllocator1> & lhs, const ::dislam_msgs::GetInitMapRequest_<ContainerAllocator2> & rhs)
{
  return lhs.initState == rhs.initState;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dislam_msgs::GetInitMapRequest_<ContainerAllocator1> & lhs, const ::dislam_msgs::GetInitMapRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dislam_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dislam_msgs::GetInitMapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dislam_msgs::GetInitMapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dislam_msgs::GetInitMapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dislam_msgs::GetInitMapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dislam_msgs::GetInitMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dislam_msgs::GetInitMapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dislam_msgs::GetInitMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ab825c7a93cd2cd861e41e9e814760c5";
  }

  static const char* value(const ::dislam_msgs::GetInitMapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xab825c7a93cd2cd8ULL;
  static const uint64_t static_value2 = 0x61e41e9e814760c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::dislam_msgs::GetInitMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dislam_msgs/GetInitMapRequest";
  }

  static const char* value(const ::dislam_msgs::GetInitMapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dislam_msgs::GetInitMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool initState\n"
"\n"
;
  }

  static const char* value(const ::dislam_msgs::GetInitMapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dislam_msgs::GetInitMapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.initState);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetInitMapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dislam_msgs::GetInitMapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dislam_msgs::GetInitMapRequest_<ContainerAllocator>& v)
  {
    s << indent << "initState: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.initState);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DISLAM_MSGS_MESSAGE_GETINITMAPREQUEST_H
