// Generated by gencpp from file dislam_msgs/Loop.msg
// DO NOT EDIT!


#ifndef DISLAM_MSGS_MESSAGE_LOOP_H
#define DISLAM_MSGS_MESSAGE_LOOP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace dislam_msgs
{
template <class ContainerAllocator>
struct Loop_
{
  typedef Loop_<ContainerAllocator> Type;

  Loop_()
    : id0(0)
    , id1(0)
    , pose()  {
    }
  Loop_(const ContainerAllocator& _alloc)
    : id0(0)
    , id1(0)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _id0_type;
  _id0_type id0;

   typedef int64_t _id1_type;
  _id1_type id1;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::dislam_msgs::Loop_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dislam_msgs::Loop_<ContainerAllocator> const> ConstPtr;

}; // struct Loop_

typedef ::dislam_msgs::Loop_<std::allocator<void> > Loop;

typedef boost::shared_ptr< ::dislam_msgs::Loop > LoopPtr;
typedef boost::shared_ptr< ::dislam_msgs::Loop const> LoopConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dislam_msgs::Loop_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dislam_msgs::Loop_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dislam_msgs::Loop_<ContainerAllocator1> & lhs, const ::dislam_msgs::Loop_<ContainerAllocator2> & rhs)
{
  return lhs.id0 == rhs.id0 &&
    lhs.id1 == rhs.id1 &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dislam_msgs::Loop_<ContainerAllocator1> & lhs, const ::dislam_msgs::Loop_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dislam_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dislam_msgs::Loop_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dislam_msgs::Loop_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dislam_msgs::Loop_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dislam_msgs::Loop_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dislam_msgs::Loop_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dislam_msgs::Loop_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dislam_msgs::Loop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a9f0334f830308ab9b1bb7ec33c20af";
  }

  static const char* value(const ::dislam_msgs::Loop_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a9f0334f830308aULL;
  static const uint64_t static_value2 = 0xb9b1bb7ec33c20afULL;
};

template<class ContainerAllocator>
struct DataType< ::dislam_msgs::Loop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dislam_msgs/Loop";
  }

  static const char* value(const ::dislam_msgs::Loop_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dislam_msgs::Loop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 id0\n"
"int64 id1\n"
"geometry_msgs/Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::dislam_msgs::Loop_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dislam_msgs::Loop_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id0);
      stream.next(m.id1);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Loop_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dislam_msgs::Loop_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dislam_msgs::Loop_<ContainerAllocator>& v)
  {
    s << indent << "id0: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id0);
    s << indent << "id1: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id1);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DISLAM_MSGS_MESSAGE_LOOP_H
